baseURL = 'https://sckn.dev/'
languageCode = 'en-us'
title = 'sckn.dev - DevOps Engineer'
theme = 'retro-terminal'
publishDir = "docs"
# Content settings
[pagination]
pagerSize = 10
enableRobotsTXT = true
# Disable Git info (not a git repository)
enableGitInfo = false

# Markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github-dark"
    lineNos = true
    codeFences = true

# Site parameters
[params]
  author = "Seckin"
  description = "DevOps Engineer specializing in cloud infrastructure, automation, and security"
  keywords = ["DevOps", "Cloud", "AWS", "Kubernetes", "Terraform", "Automation"]
  
  # Social links
  email = "hello@sckn.dev"
  github = "https://github.com/sckn"
  linkedin = "https://linkedin.com/in/sckn"
  location = "San Francisco, CA"
  
  # Site settings
  dateFormat = "January 2, 2006"
  showReadingTime = true
  showWordCount = true
  
  # Terminal theme settings
  terminalPrompt = "sckn@devops:~$"
  asciiArt = '''
     _____ _____ _  __ _   _       _            
    /  ___/  __ \ |/ /| \ | |     | |           
    \ `--.| /  \/   / |  \| |   __| | _____   __
     `--. \ |   |  <  | . ` |  / _` |/ _ \ \ / /
    /\__/ / \__/\ . \ | |\  | | (_| |  __/\ V / 
    \____/ \____/\_|\_\_| \_/  \__,_|\___| \_/  
  '''

# Menu configuration
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "About"
  url = "/#about"
  weight = 20

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 30

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 40

[[menu.main]]
  name = "Contact"
  url = "/#contact"
  weight = 50

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Privacy settings
[privacy]
  [privacy.googleAnalytics]
    disable = true
  [privacy.disqus]
    disable = true
